

all:./viaje_milindron_cercania ./viaje_milindron_insercion ./algoritmo_milindron ./tarea_milindrona

./viaje_milindron_cercania: ./viaje_milindron_cercania.cpp
	g++ -O2 ./viaje_milindron_cercania.cpp -o ./viaje_milindron_cercania

./viaje_milindron_insercion: ./viaje_milindron_cercania.cpp
	g++ -O2 viaje_milindron_insercion.cpp -o viaje_milindron_insercion

./algoritmo_milindron: ./algoritmo_milindron.cpp
	g++ -O2 algoritmo_milindron.cpp -o algoritmo_milindron

./tarea_milindrona: ./tarea_milindrona.cpp
	g++ -O2 tarea_milindrona.cpp -o tarea_milindrona
