all:./laberinto_milindron ./tsp_milindron

./laberinto_milindron: ./laberinto_milindron.cpp
	g++ -O2 ./laberinto_milindron.cpp -o ./laberinto_milindron

./tsp_milindron: ./tsp_milindron.cpp
	g++ -O2 ./tsp_milindron.cpp -o ./tsp_milindron

